"""Cerememory Python SDK -- HTTP client for the Cerememory Protocol (CMP).

Usage::

    import cerememory

    # Sync
    client = cerememory.Client("http://localhost:8420", api_key="sk-...")
    record_id = client.store("Coffee chat with Alice", store="episodic")
    memories = client.recall("coffee", limit=5)
    client.forget(record_id, confirm=True)

    # Async
    async with cerememory.AsyncClient("http://localhost:8420", api_key="sk-...") as client:
        record_id = await client.store("hello", store="episodic")
        memories = await client.recall("hello")
"""

from cerememory.client import AsyncClient, Client
from cerememory.errors import (
    CerememoryError,
    ConsolidationInProgressError,
    ContentTooLargeError,
    DecayEngineBusyError,
    ExportFailedError,
    ForgetUnconfirmedError,
    ImportConflictError,
    InternalError,
    ModalityUnsupportedError,
    RateLimitedError,
    RecordNotFoundError,
    StoreInvalidError,
    UnauthorizedError,
    ValidationError,
    VersionMismatchError,
    WorkingMemoryFullError,
)
from cerememory.types import (
    ActivationNode,
    ActivationTrace,
    Association,
    AssociationType,
    CMPHeader,
    ConflictResolution,
    ConsolidateRequest,
    ConsolidateResponse,
    ConsolidationStrategy,
    ContentBlock,
    DecayForecast,
    DecayForecastRequest,
    DecayForecastResponse,
    DecayTickRequest,
    DecayTickResponse,
    DreamTickRequest,
    DreamTickResponse,
    EmotionVector,
    EncodeBatchRequest,
    EncodeBatchResponse,
    EncodeBatchStoreRawRequest,
    EncodeBatchStoreRawResponse,
    EncodeContext,
    EncodeStoreRawRequest,
    EncodeStoreRawResponse,
    EncodeStoreRequest,
    EncodeStoreResponse,
    EncodeUpdateRequest,
    EvolutionMetrics,
    ExportArchiveResponse,
    ExportRequest,
    ExportResponse,
    FidelityState,
    ForgetRequest,
    ForgetResponse,
    GraphEdge,
    GraphNode,
    HealthResponse,
    ImportRequest,
    ImportResponse,
    ImportStrategy,
    ManualAssociation,
    MemoryContent,
    MemoryRecord,
    Modality,
    ParameterAdjustment,
    QueryMetadata,
    RawJournalRecord,
    RawSource,
    RawSpeaker,
    RawVisibility,
    ReadinessResponse,
    RecallAssociateRequest,
    RecallAssociateResponse,
    RecallCue,
    RecalledMemory,
    RecallGraphRequest,
    RecallGraphResponse,
    RecallMode,
    RecallQueryRequest,
    RecallQueryResponse,
    RecallRawQueryRequest,
    RecallRawQueryResponse,
    RecallTimelineRequest,
    RecallTimelineResponse,
    SecrecyLevel,
    SetModeRequest,
    StatsResponse,
    StoreType,
    TemporalRange,
    TimeGranularity,
    TimelineBucket,
)

__version__ = "0.2.2"

__all__ = [
    # Clients
    "Client",
    "AsyncClient",
    # Version
    "__version__",
    # Enums
    "StoreType",
    "Modality",
    "AssociationType",
    "RecallMode",
    "RawSource",
    "RawSpeaker",
    "RawVisibility",
    "SecrecyLevel",
    "TimeGranularity",
    "ConsolidationStrategy",
    "ConflictResolution",
    "ImportStrategy",
    # Core types
    "ContentBlock",
    "MemoryContent",
    "FidelityState",
    "EmotionVector",
    "Association",
    "MemoryRecord",
    "RawJournalRecord",
    "CMPHeader",
    # Encode
    "EncodeContext",
    "ManualAssociation",
    "EncodeStoreRequest",
    "EncodeStoreResponse",
    "EncodeBatchRequest",
    "EncodeBatchResponse",
    "EncodeStoreRawRequest",
    "EncodeStoreRawResponse",
    "EncodeBatchStoreRawRequest",
    "EncodeBatchStoreRawResponse",
    "ExportRequest",
    "ExportResponse",
    "ExportArchiveResponse",
    "EncodeUpdateRequest",
    # Recall
    "TemporalRange",
    "RecallCue",
    "RecallQueryRequest",
    "RecalledMemory",
    "ActivationNode",
    "ActivationTrace",
    "QueryMetadata",
    "RecallQueryResponse",
    "RecallAssociateRequest",
    "RecallAssociateResponse",
    "RecallTimelineRequest",
    "TimelineBucket",
    "RecallTimelineResponse",
    "RecallGraphRequest",
    "GraphNode",
    "GraphEdge",
    "RecallGraphResponse",
    "RecallRawQueryRequest",
    "RecallRawQueryResponse",
    # Lifecycle
    "ConsolidateRequest",
    "ConsolidateResponse",
    "DreamTickRequest",
    "DreamTickResponse",
    "DecayTickRequest",
    "DecayTickResponse",
    "SetModeRequest",
    "ForgetRequest",
    "ForgetResponse",
    "ImportRequest",
    "ImportResponse",
    # Introspect
    "ParameterAdjustment",
    "EvolutionMetrics",
    "StatsResponse",
    "DecayForecastRequest",
    "DecayForecast",
    "DecayForecastResponse",
    # Health
    "HealthResponse",
    "ReadinessResponse",
    # Errors
    "CerememoryError",
    "ValidationError",
    "StoreInvalidError",
    "ModalityUnsupportedError",
    "ForgetUnconfirmedError",
    "VersionMismatchError",
    "UnauthorizedError",
    "RecordNotFoundError",
    "ConsolidationInProgressError",
    "ImportConflictError",
    "ContentTooLargeError",
    "WorkingMemoryFullError",
    "RateLimitedError",
    "InternalError",
    "ExportFailedError",
    "DecayEngineBusyError",
]
